version: '3.8'

services:
  brand-audit-tool:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./results:/app/results
      - /dev/shm:/dev/shm  # Shared memory for Chrome
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s