[phases.setup]
nixPkgs = ['python39', 'chromium', 'chromedriver']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['mkdir -p results', 'mkdir -p static', 'mkdir -p templates']

[start]
cmd = 'gunicorn --config gunicorn.conf.py app:app'