[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['mkdir -p results', 'mkdir -p static', 'mkdir -p templates']

[start]
cmd = 'python wsgi.py'