[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements-prod.txt"]

[start]
cmd = "python railway_app.py"
EOF < /dev/null